// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18051
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DataMerger.Tests.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class MergeFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext;
        
        private TestLogConnector.TestCase testCase;
        
#line 1 "Merge.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this.testContext;
            }
            set
            {
                this.testContext = value;
            }
        }
        
        public virtual TestLogConnector.TestCase TestCase
        {
            get
            {
                return this.testCase;
            }
            set
            {
                this.testCase = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Merge", "Merging users from one repository to my local database.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (TestContext != null)
            {
                TestCase = new TestLogConnector.TestCase(GetType(), TestContext.TestName);
            }

            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Merge")))
            {
                DataMerger.Tests.Specs.MergeFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
           if (TestContext != null)
            {
                TestCase.WriteFinishedTestToTestLog(TestContext.CurrentTestOutcome.ToString());
            }

            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TestLogConnector.TestCaseAttribute("Merge one user", "John.Smith", "SMG-1375")]
        [TestLogConnector.TestCaseComment("Given:database is empty\nGiven:database does not have a user with Id 1\nWhen:Merge " +
            "User with Id 1\nThen:database has user with Id 1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Merge one user")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Merge")]
        public virtual void MergeOneUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Merge one user", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("database is empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
 testRunner.Given("database does not have a user with Id 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
    testRunner.When("Merge User with Id 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
    testRunner.Then("database has user with Id 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TestLogConnector.TestCaseAttribute("Merge one user alias. Deactivate an alias that was deleted.", "John.Smith", "SMG-1374,SMG-223")]
        [TestLogConnector.TestCaseComment(@"Given:database has User with Id 1
Given:database User with Id 1 has addresses [foo1@gr.com|Active, foo2@gr.com|Active]
When:Merge User with Id 1 and addresses [foo2@gr.com|Active, foo3@gr.com|Active]
Then:database has user Id 1 and addresses [foo1@gr.com|Inactive, foo2@gr.com|Active, foo3@gr.com|Active]")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Merge one user alias. Deactivate an alias that was deleted.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Merge")]
        public virtual void MergeOneUserAlias_DeactivateAnAliasThatWasDeleted_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Merge one user alias. Deactivate an alias that was deleted.", ((string[])(null)));
#line 15
this.ScenarioSetup(scenarioInfo);
#line 16
 testRunner.Given("database has User with Id 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 17
    testRunner.Given("database User with Id 1 has addresses [foo1@gr.com|Active, foo2@gr.com|Active]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 18
    testRunner.When("Merge User with Id 1 and addresses [foo2@gr.com|Active, foo3@gr.com|Active]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 19
 testRunner.Then("database has user Id 1 and addresses [foo1@gr.com|Inactive, foo2@gr.com|Active, f" +
                    "oo3@gr.com|Active]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TestLogConnector.TestCaseAttribute("Merge a second user. The user is not merged because someone has already claimed t" +
            "heir aliases.", "Sally.Mae", "SMG-1376")]
        [TestLogConnector.TestCaseComment(@"Given:database has User with Id 1
Given:database User with Id 1 has addresses [foo1@gr.com|Active, foo2@gr.com|Active]
When:Merge User with Id 2 and addresses [foo2@gr.com|Active, foo3@gr.com|Active]
Then:database has user Id 1 and addresses [foo1@gr.com|Active, foo2@gr.com|Active]
Then:database does not have User with Id 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Merge a second user. The user is not merged because someone has already claimed t" +
            "heir aliases.")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Merge")]
        public virtual void MergeASecondUser_TheUserIsNotMergedBecauseSomeoneHasAlreadyClaimedTheirAliases_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Merge a second user. The user is not merged because someone has already claimed t" +
                    "heir aliases.", ((string[])(null)));
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
 testRunner.Given("database has User with Id 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 25
    testRunner.Given("database User with Id 1 has addresses [foo1@gr.com|Active, foo2@gr.com|Active]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 26
    testRunner.When("Merge User with Id 2 and addresses [foo2@gr.com|Active, foo3@gr.com|Active]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 27
    testRunner.Then("database has user Id 1 and addresses [foo1@gr.com|Active, foo2@gr.com|Active]", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 28
    testRunner.Then("database does not have User with Id 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
